import * as fs from 'fs/promises';
import type { Dirent } from 'fs';
import * as path from 'path';
import { RuleInfo, SkillInfo, TargetPlatform } from './types';
import { readDocHead, toDisplayString } from './frontmatter';

/**
 * A skill's display name comes from third-party frontmatter, so strip anything
 * that could escape the target directory or be rejected by the filesystem.
 */
export function sanitizeName(name: string): string {
  const cleaned = name
    .replace(/[\\/:*?"<>|]/g, '-')
    .replace(/\.+$/, '')
    .trim();
  return cleaned || 'unnamed-skill';
}

export function getSkillsDir(projectPath: string, platform: TargetPlatform): string {
  switch (platform) {
    case 'antigravity':
      return path.join(projectPath, '.agent', 'skills');
    case 'cursor':
      return path.join(projectPath, '.cursor', 'skills');
    case 'claude-code':
    default:
      return path.join(projectPath, '.claude', 'skills');
  }
}

export function getRulesDir(projectPath: string, platform: TargetPlatform): string {
  switch (platform) {
    case 'antigravity':
      return path.join(projectPath, '.agents', 'rules');
    case 'cursor':
      return path.join(projectPath, '.cursor', 'rules');
    case 'claude-code':
    default:
      return path.join(projectPath, '.claude', 'rules');
  }
}

/**
 * Regenerate the skills index file at `{skillsDir}/SKILL.md`.
 * The index lists every installed skill with its title, when-to-use guidance,
 * and location — so an AI agent can discover the right skill without scanning
 * every subfolder.
 */
export async function generateSkillsIndex(
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const skillsDir = getSkillsDir(projectPath, platform);
  const indexPath = path.join(skillsDir, 'SKILL.md');

  let entries: Dirent[];
  try {
    entries = await fs.readdir(skillsDir, { withFileTypes: true });
  } catch {
    return;
  }

  const folders = entries.filter(e => e.isDirectory()).map(e => e.name);

  if (folders.length === 0) {
    await fs.rm(indexPath, { force: true });
    return;
  }

  const items: { name: string; description: string; location: string }[] = [];

  for (const folderName of folders) {
    const folderPath = path.join(skillsDir, folderName);
    let subEntries: Dirent[];
    try {
      subEntries = await fs.readdir(folderPath, { withFileTypes: true });
    } catch {
      continue;
    }

    const mdFiles = subEntries
      .filter(e => e.isFile() && e.name.toLowerCase().endsWith('.md'))
      .map(e => e.name);
    if (mdFiles.length === 0) continue;

    const primary =
      mdFiles.find(n => n.toUpperCase() === 'SKILL.MD') ||
      mdFiles.find(n => n.toLowerCase() === `${folderName.toLowerCase()}.md`) ||
      mdFiles.find(n => n.toUpperCase() !== 'README.MD') ||
      mdFiles[0];

    let name = folderName;
    let description = '';
    try {
      const { frontmatter } = await readDocHead(path.join(folderPath, primary));
      name = toDisplayString(frontmatter.name) || folderName;
      description = toDisplayString(frontmatter.description);
    } catch {
      // skip unreadable
    }

    items.push({
      name,
      description,
      location: `./${folderName}/${primary}`,
    });
  }

  items.sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    '# Skills Index',
    '',
    'Quick reference for every skill installed in this workspace. Each skill lives in its own folder under this directory.',
    '',
    '## How to use',
    '',
    'When a task calls for a specific capability, consult this index first to find the right skill instead of scanning every folder. Open the referenced file to read the full skill definition.',
    '',
    '## Available skills',
    '',
  ];

  for (const item of items) {
    lines.push(`### ${item.name}`);
    if (item.description) {
      lines.push(`- **When to use:** ${item.description}`);
    }
    lines.push(`- **Location:** \`${item.location}\``);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `_Total: ${items.length} skill${items.length === 1 ? '' : 's'}. Auto-generated by Lazy Skill AI Agent — do not edit manually._`,
  );
  lines.push('');

  await fs.writeFile(indexPath, lines.join('\n'), 'utf-8');
}

// --- Skills ---

export async function installSkill(
  skill: SkillInfo,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const skillsDir = getSkillsDir(projectPath, platform);
  await fs.mkdir(skillsDir, { recursive: true });

  const sourceDir = path.dirname(skill.sourcePath);
  const targetDir = path.join(skillsDir, sanitizeName(skill.name));

  await fs.rm(targetDir, { recursive: true, force: true });
  await fs.cp(sourceDir, targetDir, { recursive: true });
}

export async function uninstallSkill(
  skillName: string,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const targetDir = path.join(getSkillsDir(projectPath, platform), sanitizeName(skillName));
  await fs.rm(targetDir, { recursive: true, force: true });
}

// --- Rules ---

export async function installRule(
  rule: RuleInfo,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const rulesDir = getRulesDir(projectPath, platform);
  await fs.mkdir(rulesDir, { recursive: true });

  const ext = path.extname(rule.sourcePath) || '.md';
  const targetFile = path.join(rulesDir, `${sanitizeName(rule.name)}${ext}`);
  await fs.copyFile(rule.sourcePath, targetFile);
}

export async function uninstallRule(
  ruleName: string,
  projectPath: string,
  platform: TargetPlatform,
): Promise<void> {
  const rulesDir = getRulesDir(projectPath, platform);
  for (const ext of ['.md', '.mdc', '.txt']) {
    const target = path.join(rulesDir, `${sanitizeName(ruleName)}${ext}`);
    await fs.rm(target, { force: true });
  }
}

// --- Apply ---

export interface ApplyResult {
  skillsInstalled: number;
  skillsRemoved: number;
  rulesInstalled: number;
  rulesRemoved: number;
  errors: string[];
}

export async function applyChanges(
  allSkills: SkillInfo[],
  selectedSkillIds: Set<string>,
  allRules: RuleInfo[],
  selectedRuleIds: Set<string>,
  projectPath: string,
  platform: TargetPlatform,
): Promise<ApplyResult> {
  const result: ApplyResult = {
    skillsInstalled: 0,
    skillsRemoved: 0,
    rulesInstalled: 0,
    rulesRemoved: 0,
    errors: [],
  };

  for (const skill of allSkills) {
    const should = selectedSkillIds.has(skill.id);
    if (should && !skill.isInstalled) {
      try {
        await installSkill(skill, projectPath, platform);
        result.skillsInstalled++;
      } catch (e) {
        result.errors.push(`Skill ${skill.name}: ${e}`);
      }
    } else if (!should && skill.isInstalled) {
      try {
        await uninstallSkill(skill.name, projectPath, platform);
        result.skillsRemoved++;
      } catch (e) {
        result.errors.push(`Skill ${skill.name}: ${e}`);
      }
    }
  }

  for (const rule of allRules) {
    const should = selectedRuleIds.has(rule.id);
    if (should && !rule.isInstalled) {
      try {
        await installRule(rule, projectPath, platform);
        result.rulesInstalled++;
      } catch (e) {
        result.errors.push(`Rule ${rule.name}: ${e}`);
      }
    } else if (!should && rule.isInstalled) {
      try {
        await uninstallRule(rule.name, projectPath, platform);
        result.rulesRemoved++;
      } catch (e) {
        result.errors.push(`Rule ${rule.name}: ${e}`);
      }
    }
  }

  // Regenerate the skills index so AI agents can discover installed skills quickly
  try {
    await generateSkillsIndex(projectPath, platform);
  } catch (e) {
    result.errors.push(`Skills index: ${e}`);
  }

  return result;
}
